# Generated by Django 3.0 on 2019-12-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourHeadHunter', '0002_auto_20191214_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='to_company',
            field=models.BooleanField(blank=True, null=True, verbose_name='Откликнуться на вакансию от компании'),
        ),
    ]
